# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: glove_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='glove_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10glove_data.proto\"*\n\x07Point3D\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\x12\t\n\x01z\x18\x03 \x01(\x11\"-\n\x11TactileSensorData\x12\x18\n\x06points\x18\x01 \x03(\x0b\x32\x08.Point3D\"O\n\x0e\x41llSensorsData\x12#\n\x07sensors\x18\x01 \x03(\x0b\x32\x12.TactileSensorData\x12\x18\n\x10resistor_sensors\x18\x02 \x03(\x05\x62\x06proto3')
)




_POINT3D = _descriptor.Descriptor(
  name='Point3D',
  full_name='Point3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Point3D.x', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Point3D.y', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Point3D.z', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=62,
)


_TACTILESENSORDATA = _descriptor.Descriptor(
  name='TactileSensorData',
  full_name='TactileSensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='TactileSensorData.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=109,
)


_ALLSENSORSDATA = _descriptor.Descriptor(
  name='AllSensorsData',
  full_name='AllSensorsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensors', full_name='AllSensorsData.sensors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resistor_sensors', full_name='AllSensorsData.resistor_sensors', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=190,
)

_TACTILESENSORDATA.fields_by_name['points'].message_type = _POINT3D
_ALLSENSORSDATA.fields_by_name['sensors'].message_type = _TACTILESENSORDATA
DESCRIPTOR.message_types_by_name['Point3D'] = _POINT3D
DESCRIPTOR.message_types_by_name['TactileSensorData'] = _TACTILESENSORDATA
DESCRIPTOR.message_types_by_name['AllSensorsData'] = _ALLSENSORSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Point3D = _reflection.GeneratedProtocolMessageType('Point3D', (_message.Message,), dict(
  DESCRIPTOR = _POINT3D,
  __module__ = 'glove_data_pb2'
  # @@protoc_insertion_point(class_scope:Point3D)
  ))
_sym_db.RegisterMessage(Point3D)

TactileSensorData = _reflection.GeneratedProtocolMessageType('TactileSensorData', (_message.Message,), dict(
  DESCRIPTOR = _TACTILESENSORDATA,
  __module__ = 'glove_data_pb2'
  # @@protoc_insertion_point(class_scope:TactileSensorData)
  ))
_sym_db.RegisterMessage(TactileSensorData)

AllSensorsData = _reflection.GeneratedProtocolMessageType('AllSensorsData', (_message.Message,), dict(
  DESCRIPTOR = _ALLSENSORSDATA,
  __module__ = 'glove_data_pb2'
  # @@protoc_insertion_point(class_scope:AllSensorsData)
  ))
_sym_db.RegisterMessage(AllSensorsData)


# @@protoc_insertion_point(module_scope)
